# Report: instruction-set dependent tokens in the public headers.
#
#   cmake -DHEADER_DIR=<include/frsr/roaring> -P header_isa_tokens.cmake
#
# Counts, per header, occurrences of tokens whose meaning depends on the
# instruction-set options a translation unit is compiled with: ISA predefined
# macros, intrinsics, intrinsic headers and target attributes. Such a header
# preprocesses or compiles differently under different options, so every
# translation unit including it must use the library's options. Always succeeds.

if(NOT HEADER_DIR)
    get_filename_component(HEADER_DIR "${CMAKE_CURRENT_LIST_DIR}/../include/frsr/roaring" ABSOLUTE)
endif()

set(_columns SSE4_2 AVX2 AVX512 BMI mm mm256 mm512 immintrin nmmintrin target tgt_macro)
set(_label_SSE4_2    "__SSE4_2__")
set(_label_AVX2      "__AVX2__")
set(_label_AVX512    "__AVX512*")
set(_label_BMI       "__BMI*")
set(_label_mm        "_mm_")
set(_label_mm256     "_mm256_")
set(_label_mm512     "_mm512_")
set(_label_immintrin "immintrin")
set(_label_nmmintrin "nmmintrin")
set(_label_target    "target(")
set(_label_tgt_macro "*_KERNEL/HELPER")
set(_regex_SSE4_2    "__SSE4_2__")
set(_regex_AVX2      "__AVX2__")
set(_regex_AVX512    "__AVX512")
set(_regex_BMI       "__BMI")
set(_regex_mm        "_mm_")
set(_regex_mm256     "_mm256_")
set(_regex_mm512     "_mm512_")
set(_regex_immintrin "immintrin")
set(_regex_nmmintrin "nmmintrin")
# __attribute__((target(...))), [[gnu::target(...)]] and [[using gnu: target(...)]]
set(_regex_target    "__attribute__[ \t]*\\(\\([ \t]*target|gnu::[ \t]*target[ \t]*\\(|using[ \t]+gnu[ \t]*:[ \t]*target[ \t]*\\(")
# the library's own target-attribute macros (FRSR_ROARING_X86_V4_KERNEL, ...)
set(_regex_tgt_macro "FRSR_ROARING_[A-Z0-9_]+_(KERNEL|HELPER)")

function(_pad out text width)
    string(LENGTH "${text}" _len)
    set(_result "${text}")
    while(_len LESS width)
        string(APPEND _result " ")
        math(EXPR _len "${_len} + 1")
    endwhile()
    set(${out} "${_result}" PARENT_SCOPE)
endfunction()

file(GLOB _headers LIST_DIRECTORIES false "${HEADER_DIR}/*.hpp")
list(SORT _headers)

set(_name_width 26)
set(_col_width 16)
_pad(_line "header" ${_name_width})
foreach(_c IN LISTS _columns)
    _pad(_cell "${_label_${_c}}" ${_col_width})
    string(APPEND _line "${_cell}")
endforeach()
string(APPEND _line "total")
message("frsr::roaring header ISA-token lint (occurrences, comments included) in ${HEADER_DIR}")
message("${_line}")

set(_dependent_headers 0)
set(_grand_total 0)
foreach(_c IN LISTS _columns)
    set(_sum_${_c} 0)
endforeach()
foreach(_header IN LISTS _headers)
    file(READ "${_header}" _content)
    get_filename_component(_name "${_header}" NAME)
    _pad(_line "${_name}" ${_name_width})
    set(_total 0)
    foreach(_c IN LISTS _columns)
        string(REGEX MATCHALL "${_regex_${_c}}" _hits "${_content}")
        list(LENGTH _hits _n)
        math(EXPR _total "${_total} + ${_n}")
        math(EXPR _sum_${_c} "${_sum_${_c}} + ${_n}")
        _pad(_cell "${_n}" ${_col_width})
        string(APPEND _line "${_cell}")
    endforeach()
    string(APPEND _line "${_total}")
    message("${_line}")
    math(EXPR _grand_total "${_grand_total} + ${_total}")
    if(_total GREATER 0)
        math(EXPR _dependent_headers "${_dependent_headers} + 1")
    endif()
endforeach()

_pad(_line "all headers" ${_name_width})
foreach(_c IN LISTS _columns)
    _pad(_cell "${_sum_${_c}}" ${_col_width})
    string(APPEND _line "${_cell}")
endforeach()
string(APPEND _line "${_grand_total}")
message("${_line}")
list(LENGTH _headers _header_count)
message("${_dependent_headers} of ${_header_count} headers contain instruction-set dependent tokens")
